### ISSUE TITLE
Fix Page Layout

### ISSUE THREAD

**Issue by uinnnnnn** [IPFS-Blog/Frontend#24]
- [x] 背景
- [x] Logo
- [x] 首頁
- [x] 導覽列
   

| 調整前 | 調整後| 
| -------- | -------- | 
|![image](https://github.com/IPFS-Blog/Frontend/assets/113336518/772588f6-60ee-467a-accd-9f1e016487ca) | ![1683844349369](https://github.com/IPFS-Blog/Frontend/assets/113336518/aa6dccd2-d540-4f74-9a34-75ddc018d85e) | 

| 調整前 | 調整後| 
| -------- | -------- | 
|![image](https://github.com/IPFS-Blog/Frontend/assets/113336518/1b1ba08a-b955-40d5-87cf-2c4cd9de67da)  | ![1683844487138](https://github.com/IPFS-Blog/Frontend/assets/113336518/67bfecdb-1049-4547-a835-1acec22283b8) | 

- [x] 個人首頁、瀏覽使用者頁面

| 調整前 | 調整後| 
| -------- | -------- | 
| ![image](https://user-images.githubusercontent.com/113336518/236695974-7264e389-0b26-4c53-b517-fea2c13922af.png)    | ![image](https://user-images.githubusercontent.com/113336518/236696033-843460f3-68b7-4424-9f8f-0176b41e5756.png)  | 

| 調整前 | 調整後| 
| -------- | -------- | 
|![image](https://github.com/IPFS-Blog/Frontend/assets/113336518/4139d9cf-02b6-456b-8d83-e073d1e5d2e7)    |![1683836519227](https://github.com/IPFS-Blog/Frontend/assets/113336518/00ab47e7-de57-4000-902a-2928d006cf2b)|   

- [x] 單一文章頁面

| 淺色 | 深色| 
| -------- | -------- | 
| ![image](https://github.com/IPFS-Blog/Frontend/assets/113336518/714ccf81-d2d2-4e71-8719-35cf1e3771ae) | ![image](https://github.com/IPFS-Blog/Frontend/assets/113336518/9c1f7490-6e79-4890-ac15-bf7ea3526033)| 

[Figma畫面設計](https://www.figma.com/file/OKoEbg15J9AOIYucOpg3CK/%E6%98%A0%E5%A6%82-UNI's-team-library?type=design&node-id=1015-4411&t=OpE613zBK0FYVkcB-0)

**Comment by uinnnnnn** [comment]
- [ ] 個人首頁、瀏覽使用者頁面
- 卡片改成點擊翻轉
- 背景也換成圖片div(可以用(換背景))

**Comment by uinnnnnn** [comment]
Alert 需要改成幾秒後就消失，還有可以堆疊

**Comment by uinnnnnn** [comment]
加入我的區塊鏈的 Alert 看能不能 改成顯示一次，按確認後就不要再出現了

>ps: 如果想要讓使用者再確認有沒有加入成功，可以在加確認有無的

**Comment by uinnnnnn** [comment]
- [] 編輯個人資料 需要處理錯誤
> 400 名稱已被使用 。
> 400 此信箱已被註冊，請換信箱註冊。
顯示給使用者

**Comment by uinnnnnn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [整體畫面-排版優化](https://trello.com/c/VgySRuQK/87-%E6%95%B4%E9%AB%94%E7%95%AB%E9%9D%A2-%E6%8E%92%E7%89%88%E5%84%AA%E5%8C%96)

**Comment by uinnnnnn** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [整體畫面-排版優化](https://trello.com/c/VgySRuQK/87-%E6%95%B4%E9%AB%94%E7%95%AB%E9%9D%A2-%E6%8E%92%E7%89%88%E5%84%AA%E5%8C%96)

**Comment by a20688392** [comment]
於登入的時候觸發此 metamask 錯誤回應
![image](https://github.com/IPFS-Blog/Frontend/assets/77681849/73da4108-c173-4930-bda7-5d2b4abf6962)
https://github.com/MetaMask/metamask-extension/issues/10085
解決方法，抓獲錯誤並彈跳視窗請解鎖 metamask

**Comment by a20688392** [comment]
刪除一篇草稿文章，卻清除所有
![error1](https://github.com/IPFS-Blog/Frontend/assets/77681849/6358809a-299a-4c24-9b81-abbdc9f78d68)
